### ISSUE TITLE
Possible Targets

### ISSUE THREAD

**Issue by fpedd** [tum-ei-eda/muriscv-nn#10]
There are a number of academic vector cores out there:
#### Low Power / Embedded
- 2022 ETH Zurich [Spatz: A Compact Vector Processing Unit for High-Performance and Energy-Efficient Shared-L1 Clusters](https://arxiv.org/pdf/2207.07970.pdf) RVV 1.0 Zve32x embedded integer subset
- 2021 TU Wien [Vicuna: A Timing-Predictable RISC-V Vector Coprocessor](https://publik.tuwien.ac.at/files/publik_296583.pdf) RVV 0.10
- 2021 Univ. of Beirut [Arrow: A RISC-V Vector Accelerator for Machine Learning
Inference](https://arxiv.org/pdf/2107.07169.pdf) RVV 0.9
- 2020 Univ. of Southampton [A Minimal RISC-V Vector Processor for Embedded Systems](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9232940) RVV 0.8 (see [GitHub repo](https://github.com/AI-Vector-Accelerator/x-ava-core/tree/master))

#### Application Level
- 2020 ETH Zurich [Ara: A 1-GHz+ Scalable and Energy-Efficient RISC-V Vector Processor With Multiprecision Floating-Point Support in 22-nm FD-SOI](https://arxiv.org/pdf/1906.00478.pdf) [GitHub](https://github.com/pulp-platform/ara) RVV 0.10
- 2022 Barcelona Supercomputing Center [Vitruvius+: An Area-Efficient RISC-V Decoupled Vector Accelerator for High Performance Computing](https://open-src-soc.org/2022-05/media/slides/4th-RISC-V-Meeting-2022-05-04-11h00-Francesco-Minervini.pdf) RVV0.7.1
- 2020 [RISC-V2: A Scalable RISC-V Vector Processor](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9181071) 
- 2018 UC Berkley [Hwacha V4: Decoupled Data Parallel Custom Extension](https://riscv.org/wp-content/uploads/2018/12/Hwacha-A-Data-Parallel-RISC-V-Extension-and-Implementation-Schmidt-Ou-.pdf) and [GitHub Repo](https://github.com/ucb-bar/hwacha)
- 2021 [Development of RISC-V Based Soft-core Processor with Scalable Vector Extension for Embedded System](https://dl.acm.org/doi/pdf/10.1145/3468081.3471061) and [GitHub Repo](https://github.com/klessydra/Morph)
___

On the commercial side, we have the following:
#### Commercial IP Cores:
- Andes [NX27V](http://www.andestech.com/en/products-solutions/andescore-processors/riscv-nx27v/)
- Alibaba [OpenC906](https://github.com/T-head-Semi/openc906) and [OpenC910](https://github.com/T-head-Semi/openc910) RVV0.7.1
- SiFive [P270](https://sifive.cdn.prismic.io/sifive/859c28c0-8bd5-4fc4-9113-a25a2a89bf9c_P270+Data+Sheet.pdf) and [X280](https://sifive.cdn.prismic.io/sifive/62e0df53-be02-4b50-b211-aa55b7042fc8_x280-datasheet-21G3.pdf) RVV 1.0
- NSITEXE,Inc. [NS 72 ](https://www.nsitexe.com/en/news/archives/20220802/) and [DR1000C](https://www.nsitexe.com/en/news/archives/20220414-1/) RVV 1.0
#### Actual Hardware:
- [Allwinner D1](https://linux-sunxi.org/D1) based on the OpenC906, RVV0.7.1

___

#### General Notes
The larger vector cores probably compare to ARM's Scalable Vector Extension (SVE, aka Neon), while the smaller vector cores appear to target a similar domain as ARM's embedded vector extension for Cortex-M microcontroller (MVE, aka Helium). This is also the vector extension used in CMSIS-NN. However, the only core with MVE appears to be the Cortex-M55. And there are, to this date, no open performance numbers available. 
ARM's DSP extension for Cortex-M can be compared to RISC-V's packed extension.

**Comment by PhilippvK** [comment]
Closing as outdated
