### ISSUE TITLE
Self-contained releases

### ISSUE THREAD

**Issue by christian-herber-nxp** [tum-ei-eda/muriscv-nn#15]
I tried running the provided scripts,  but this proves quite difficult due to policies, proxies etc. - Just to many scripts downloading stuff from somewhere.
Is there a chance that when you create a release, you build a self-contained package that contains the necessary toolchains and simulators etc?

**Comment by PhilippvK** [comment]
Would a docker-image containing all the dependencies work?

**Comment by christian-herber-nxp** [comment]
that would be a good idea. another thing is that iirc, the build scripts provided always run everything, i.e. use all compilers, all simulators and all extensions. Maybe one could modularize or parameterize this a bit. Then if I have to download things manually, I could be a bit more selective.

**Comment by fabianpedd** [comment]
What kind of config are you interested in? Do you want to use the V / P ext? Which simulator would you like to run on: OVPsim / Spike? The easiest way, for now, to run only a subset would probably be to just remove the parts that you don't need from the scripts.

**Comment by fabianpedd** [comment]
Beyond that and depending on your OS, you might need to build some of the dependencies yourself (toolchains, Spike simulator). All the binaries we provide to download are only tested on 18.04 (see GitHub CI).

**Comment by christian-herber-nxp** [comment]
This is less of a really blocking thing than an annoyance. Modifying git tracked files is always a bit annoying and lead sooner or later to such a modified file being part of a commit. The better solution is to parameterize the script, so that I could pass the requirement e.g. to build with V, LLVM, and Spike. The number of permutations will just grow, so I think such a solution will scale better.

**Comment by PhilippvK** [comment]
I have just published our first official tag: https://github.com/tum-ei-eda/muriscv-nn/releases/tag/v0.1.0

Plans for further releases can be found under Milestones: https://github.com/tum-ei-eda/muriscv-nn/milestones
