### ISSUE TITLE
TFLM and tflm directories in /Integration should be changed

### ISSUE THREAD

**Issue by christian-herber-nxp** [tum-ei-eda/muriscv-nn#16]
two directories with the same name in a different case can create issues depending on the OS, and for sure doesnt help to understand whats beneath. Suggest to change this

**Comment by fabianpedd** [comment]
Yes, I agree 100%. I will need to invest more time to refactor large parts (naming, cleaning things up, working on robust integration). I am currently on an exchange semester, that's why I haven't been able to work on this, but I will get back to this asap!

**Comment by PhilippvK** [comment]
Fixed in https://github.com/tum-ei-eda/muriscv-nn/pull/74/commits/cd66df83517d8d887bf4b1878b1864ed4eeabec8

Will be on `main` once #74 is merged.

Sorry for the delay ;)
