### ISSUE TITLE
tflm no commit specified

### ISSUE THREAD

**Issue by christian-herber-nxp** [tum-ei-eda/muriscv-nn#17]
The tflm integration requires checking out tflm, and applying a patch, but doesn't state onto which commit.
Specifying this would be the bare minimum, but the cleaner solution would be to provide an already patched fork on github (and potentially include this as a submodule)

**Comment by fabianpedd** [comment]
Yes, you are right! The current integration is very hacky.

**Comment by christian-herber-nxp** [comment]
could you just push a branch on your fork of tflm that contains the changes? that could enable some next steps

**Comment by PhilippvK** [comment]
The Integration tests in the CI now run against latest TFLM/TVM and a fixed commit that is known to work. In the future we would like to add a section in the README which lists combinations of muRISCV-NN/CMSIS-NN/TFLM/TVM which are compatible.

See https://github.com/tum-ei-eda/muriscv-nn/blob/master/.github/workflows/integration_tests.yml#L32 for example.

**Comment by PhilippvK** [comment]
The new [`COMPATIBILITY.md`](https://github.com/tum-ei-eda/muriscv-nn/blob/master/COMPATIBILITY.md) should help to document the supported versions of LLVM/GCC/TVM/TFLM/CMSIS-NN. I will try to update the tables after every Release.
