### ISSUE TITLE
unity.c:(.text+0x1cd8): undefined reference to `__subsf3'

### ISSUE THREAD

**Issue by upsDreamer** [tum-ei-eda/muriscv-nn#34]
When I run the build.sh I got this unity error

**Comment by upsDreamer** [comment]
Sorry for my late reply. I use the following command
./build.sh -t GCC -b Release -s Spike -e 1024
I used the download script download_rv32gc.sh to download the riscv tool
and I got some error such as:
muriscv-nn/Toolchain/rv32gc/bin/../lib/gcc/riscv32-unknown-elf/11.1.0/../../../../riscv32-unknown-elf/bin/ld: unity.c:(.text+0x1cfc): undefined reference to `__subsf3'

**Comment by PhilippvK** [comment]
@upsDreamer If I understand correctly you have only downloaded the scalar riscv gcc so far aka. `rv32gc`. To compile for the full vector extension make sure to also download the `rv32gcv` toolchain with the provided scripts. If you want to make use of the embedded vector extension (Zve32x, no (V)FPU) add a `-i` to the arguments and download the `rv32imv` toolchain as well.

BTW: The `-e` flag should be used to specify the EEW which shall be either 32 or 64. If you want to configure the VLEN instead, please make use of the `-l 1024` flag.

I hope that you can make it work. If further issues show up, please provide as many details as possible to allow me reproducing the issue.
